project:
  type: website
  output-dir: docs


editor:
  render-on-save: true

language: 
  search-text-placeholder: Search (Press S key for shortcut)

website:
  title: "ğŸ“„ MiMo Docs"
  search: true
  page-navigation: true
  navbar:
    left:
      - Links to web apps...  
      - text: âš™ï¸ MiMo App
        href: https://www.mimolanguageanalysis.uk
      - text: ğŸ“ˆ MiMo Norms
        href: https://norms.mimolanguageanalysis.uk
    right: 
      - text: "âœ‰ï¸ Nick G Riches"
        href: "mailto:nick.riches@gmail.com"
      - text: "ğŸŒ github repo"
        href: "https://github.com/nickriches/MiMoShinyLive"
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "ğŸ§± Basics"
      contents:
      - text: "Intro"
        href: index.qmd
      - transcription.qmd
      - entering_data.qmd
      - languages.qmd
      - morphological_analysis.qmd
      - other_syntactic_metrics.qmd
      - lexical_analysis.qmd
      - Colour_highlights.qmd
    - section: "ğŸ” Exploring your data"
      contents:
      - filtering.qmd
      - sorting.qmd
      - metrics.qmd
      - tags.qmd
    - section: "ğŸ“ˆ MiMo Norms"
      contents:
      - plotting_norms.qmd
      - plotting_a_single_child.qmd
    - section: "ğŸ‘©ğŸ½â€ğŸ’» Techie stuff"
      contents:
      - is_my_data_safe.qmd
      - making_copies.qmd
    - section: "ğŸ¬ Instructional videos"
      contents:
      - instructional_videos.qmd
    - section: "ğŸ™ğŸ½ Acknowledgements"
      contents:
      - acknowledgements.qmd


format:
  html:
    code-overflow: wrap
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true      



